# Uncomment this line to define a global platform for your project
platform :ios, "9.0"
use_frameworks!

def pods
    pod 'Alamofire', '~> 4.0'
    pod 'AlamofireImage', '~> 3.3'
    pod 'SwiftyMarkdown'
end

target 'Xapo' do

  # Pods for Vamo
  pods

end
